spring.application.name=academic-copilot

# =========================================================
# DATABASE
# =========================================================

spring.datasource.url=jdbc:postgresql://localhost:5432/academic_copilot
spring.datasource.username=academic_user
spring.datasource.password=academic_pass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# =========================================================
# FILE UPLOAD
# =========================================================

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


# =========================================================
# GEMINI EMBEDDING
# =========================================================

spring.ai.google.genai.embedding.api-key=${GEMINI_API_KEY}


# =========================================================
# QDRANT
# =========================================================

spring.ai.vectorstore.qdrant.host=localhost
spring.ai.vectorstore.qdrant.port=6334

# New collection for user/material scoped vectors
spring.ai.vectorstore.qdrant.collection-name=academic_materials_v2

spring.ai.vectorstore.qdrant.initialize-schema=true
spring.ai.vectorstore.qdrant.use-tls=false


# =========================================================
# GEMINI CHAT
# =========================================================

spring.ai.google.genai.api-key=${GEMINI_API_KEY}

spring.ai.google.genai.chat.model=gemini-3.5-flash-lite